apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-depl
spec:
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
      - name: story
        imagePullPolicy: Always
        image: gagandeep39/k8s-node-persist:2
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
---

apiVersion: v1
kind: Service
metadata:
  name: story
spec:
  selector:
    app: story
  type: LoadBalancer
  ports:
  - port: 3000
    protocol: 'TCP'
    targetPort: 3000
